// <auto-generated />
using System;
using DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220720185759_AddPeriodoAcademicoTable")]
    partial class AddPeriodoAcademicoTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DataAccess.Data.Entities.Competencia", b =>
                {
                    b.Property<int>("Competencia_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Competencia_Id"), 1L, 1);

                    b.Property<string>("Competencia_Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("Programa_Id")
                        .HasColumnType("int");

                    b.HasKey("Competencia_Id");

                    b.HasIndex("Programa_Id");

                    b.HasIndex("Competencia_Nombre", "Programa_Id")
                        .IsUnique()
                        .HasFilter("[Programa_Id] IS NOT NULL");

                    b.ToTable("Competencias");
                });

            modelBuilder.Entity("DataAccess.Data.Entities.PeriodoAcademico", b =>
                {
                    b.Property<int>("Periodo_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Periodo_Id"), 1L, 1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Periodo_FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Periodo_FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Periodo_Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Periodo_Id");

                    b.HasIndex("Periodo_Nombre", "Periodo_Id")
                        .IsUnique();

                    b.ToTable("PeriodoAcademicos");
                });

            modelBuilder.Entity("DataAccess.Data.Entities.Programa", b =>
                {
                    b.Property<int>("Programa_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Programa_Id"), 1L, 1);

                    b.Property<bool>("IsActivo")
                        .HasColumnType("bit");

                    b.Property<string>("Programa_Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Programa_Id");

                    b.HasIndex("Programa_Nombre")
                        .IsUnique();

                    b.ToTable("Programas");
                });

            modelBuilder.Entity("PeriodoAcademicoPrograma", b =>
                {
                    b.Property<int>("PeriodoAcademicosPeriodo_Id")
                        .HasColumnType("int");

                    b.Property<int>("ProgramasPrograma_Id")
                        .HasColumnType("int");

                    b.HasKey("PeriodoAcademicosPeriodo_Id", "ProgramasPrograma_Id");

                    b.HasIndex("ProgramasPrograma_Id");

                    b.ToTable("PeriodoAcademicoPrograma");
                });

            modelBuilder.Entity("DataAccess.Data.Entities.Competencia", b =>
                {
                    b.HasOne("DataAccess.Data.Entities.Programa", "Programa")
                        .WithMany("Competencias")
                        .HasForeignKey("Programa_Id");

                    b.Navigation("Programa");
                });

            modelBuilder.Entity("PeriodoAcademicoPrograma", b =>
                {
                    b.HasOne("DataAccess.Data.Entities.PeriodoAcademico", null)
                        .WithMany()
                        .HasForeignKey("PeriodoAcademicosPeriodo_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Data.Entities.Programa", null)
                        .WithMany()
                        .HasForeignKey("ProgramasPrograma_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccess.Data.Entities.Programa", b =>
                {
                    b.Navigation("Competencias");
                });
#pragma warning restore 612, 618
        }
    }
}
